### ISSUE TITLE
[Bug]: 404 error at URL: /txns/qk3WzB5ype7aQSQYLcMeK5i2HCwKtQwdGux2TOZbqgw

### ISSUE THREAD

**Issue by ghost** [helium/explorer#1028]
### What happened?

A bug happened!
On Friday, July 22, 2022 I transferred 12.98 HNT's and received them in my wallet "14j2NFU1YYB1MhGcD2Ve8zqh1AVCnVu6iGm6iUWTqyhUmrz2D6d", the HNT's were added to my wallet however the transaction hash "qk3WzB5ype7aQSQYLcMeK5i2HCwKtQwdGux2TOZbqgw" results in "404 — Transaction Not Found"

I checked this transaction from different browsers and mobile/desktop, all results in 404 error, will this effect the HNT's in my wallet? does the lack of this hash not showing in explorer has any bearing on my future transactions?

Explorer shows received tokens but with no transaction hash or amount of tokens.

https://explorer.helium.com/accounts/14j2NFU1YYB1MhGcD2Ve8zqh1AVCnVu6iGm6iUWTqyhUmrz2D6d/activity

![image](https://user-images.githubusercontent.com/97270167/185711385-dfbbc0a9-b956-4147-9b91-d2730ccc025a.png)

### URL

https://explorer.helium.com/txns/qk3WzB5ype7aQSQYLcMeK5i2HCwKtQwdGux2TOZbqgw

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by matthewcarlreetz** [comment]
@Dimoly how did you transfer the HNT?

**Comment by ghost** [comment]
@matthewcarlreetz From crypto com exchange.

**Comment by cokes518** [comment]
Hi, I see that the transaction hash you pasted (qk3WzB5ype7aQSQYLcMeK5i2HCwKtQwdGux2TOZbqgw) actually failed because it was a duplicate transaction of one that cleared on 7/22. Perhaps to you submitted the transaction twice by mistake. 

this is the response on the API
<img width="678" alt="image" src="https://user-images.githubusercontent.com/19331274/186280544-add89464-2268-41a1-a90e-f73c36088115.png">


looks like nothing to be concerned about.

**Comment by cokes518** [comment]
reopening this as i look through the bug backlog, looks like this may be related to #1024

**Comment by ghost** [comment]
@cokes518 Thanks for looking into this.

**Comment by cokes518** [comment]
@Dimoly i took a look at this, and while the transaction did clear, the hash is not displaying on explorer as you correctly stated. Unfortunately, since this transaction happened over a month ago, there are no logs for us to look at so I cannot dig into this any further. 

if you see this again, please file another bug. thanks
