### ISSUE TITLE
Challenge Interval should use the chain var value

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#142]
On hotspot checklists, the challenge interval is hardcoded to `60`. We should have the number pulled from the chain var instead.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/19331274/104663941-ea34d400-5682-11eb-809c-78a4ed43d1a2.png">

fwiw, challenge interval is 240 right now.

**Comment by anthonyra** [comment]
I'd like to take a stab at this one for the Hackathon

**Comment by danielcolinjames** [comment]
@anthonyra  amazing! sorry just saw your comment now. assigned you to this one

**Comment by danielcolinjames** [comment]
@anthonyra 

following up on [conversation in Discord](https://discord.com/channels/404106811252408320/750533049623773304/803385549057687602):

so how I might do it is to add the chain var fetch to the getHotspotActivity() function on line 96 in [hotspotid].js, and then add it to the hotspotActivity object that gets set at the end of that function

but like you said, it shouldn't change too frequently, so doing it in getStaticProps should work nicely too. I guess I hesitated because you can only do getStaticProps at the page level which felt like too big of a scope, but the hotspot page is the only place this checklist should appear, and we can always remove it in the event that the checklist is collapsed by default or something else that would make it unnecessary for the page to always fetch this

so I think either way should be fine since it'll be a very small request either way :)

**Comment by anthonyra** [comment]
Pulling it higher to be loaded once per session might be useful too. If you pull it at that high level (I'm use to just using a basic React context for this) you'd be able to pull any chain var in the future from that too. So thinking about future Hex concerns it might be useful?

**Comment by anthonyra** [comment]
My other thought's too since it built serverside then and pulled by all future requests that you wouldn't hit that endpoint for every hotspot page render during any session... but I'm not actually 100% sure if it worked that way haha

**Comment by danielcolinjames** [comment]
good point! yeah if you were hitting `https://api.helium.io/v1/vars` instead of `https://api.helium.io/v1/vars/:name` for sure, we could use all of them on that page in the future 👍 

and yeah true, I think unfortunately it'll still load once for each unique hotspot page, but you can set `revalidate` in `getStaticProps` to something like 24 hours worth of seconds for that one, so it will know to not update very often for each hotspot page. we have been looking into better ways to cache those between pages though because yeah, for something semi-stable like a chain var it shouldn't necessarily have to ping the API on every page load

**Comment by anthonyra** [comment]
When it comes to working with `getStaticProps` I assume running a local dev environment won't react the same as when it's on the server will it? Is that why there's a Heroku run environment for Explorer? I'm also getting an error while working with the hotspots page..

`Error {status: 403, url: "https://api.mapbox.com/fonts/v1/petermain/Input Mo…ODAwbnQzbXAzOWNrZGxlbHMifQ.t-VK2txgBsv1l691rnYUJA", name: "e", message: "Forbidden"}`

**Comment by danielcolinjames** [comment]
> When it comes to working with getStaticProps I assume running a local dev environment won't react the same as when it's on the server will it? Is that why there's a Heroku run environment for Explorer?

that's right, it won't function quite the same in the local environment, but it should make all the requests again on every refresh of the page

> I'm also getting an error while working with the hotspots page..
>Error {status: 403, url: "https://api.mapbox.com/fonts/v1/petermain/Input Mo…ODAwbnQzbXAzOWNrZGxlbHMifQ.t-VK2txgBsv1l691rnYUJA", name: "e", message: "Forbidden"}

and hmm yeah the Mapbox error you can probably ignore for now (or find a way to make it stop yelling at you), I think that's just because of the environment variables. I added some steps to the README for adding a mapbox API key which might make that go away

**Comment by cokes518** [comment]
hi @anthonyra  ! Our hackathon has officially ended but we'd like to give you an opportunity to complete this open issue and receive credit for the work. 

Please make sure to submit the finished PR by March 8! Thank you for your contributions! 💪

**Comment by danielcolinjames** [comment]
fixed by #618
