### ISSUE TITLE
Prettify token_burn_v1

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#149]
https://explorer.helium.com/txns/Dm7WReN3RpL0g5grUojWwavJJiweBEOWMkXjrXnPcNA

Can we also display the oracle price at the time of the burn?

**Comment by filoozom** [comment]
I'll take this one! 🙂

**Comment by danielcolinjames** [comment]
@filoozom  awesome! assigned it to you 🔥 

if you're looking for how to get the oracle price at the block height, check out line 236 in `/components/ExportCSV/utils.js`

and if you're looking for inspiration on the design / layout, check out the other transaction types in `/components/Txns` :)

**Comment by filoozom** [comment]
Hi, I was already having a look at all of these! 😁 

I was just thinking that design isn't my best domain though, so I guess we'll see what I can come up with. Any suggestions?

**Comment by danielcolinjames** [comment]
no worries! for the transaction detail pages, I would probably just start with another one that's similar enough and then remove all the stuff that doesn't apply to this one (e.g. no need for a map). for example, the PaymentV1.js might be a good file to just copy and rename to TokenBurnV1.js and then adjust the table to suit the fields that come through a token burn transaction, make all the addresses clickable, add the little circle account icon etc :)

and then height, hash, time, can probably be omitted from the table since they're already shown in the top of the page

**Comment by danielcolinjames** [comment]
oh and just thought of one more thing, if you get a chance to update the TxnTag as well to add one for "token_burn_v1", @cokes518 can probably give you some guidance on a colour to pick 😄   (or you can YOLO one in and we'll check after)

**Comment by cokes518** [comment]
please yolo the color and I'll check it out in the pull request.
