### ISSUE TITLE
Prettify state_channel_open_v1 transactions

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#193]
https://explorer.helium.com/txns/U8Hezu37HwU0Z7zn9Ad8p0keRD8e-NZ2mNtpNFGnwuw

Make time stamp human readable
add link to owner account
add link to block height
simplify fee to show DCs
simplify amount to show HNT

**Comment by danielcolinjames** [comment]
notes for hackathon participants:
- look at other transactions in /components/Txns/ folder and use them as a starting point
- you can probably just not show the block height and timestamp since they're included in the overall layout

feel free to reach out if you have any questions! 😄  (I'm `@dcj` on the [Helium Discord](https://discord.gg/helium))

**Comment by MohdImran001** [comment]
@cokes518 and @danielcolinjames, I would love to work on it.

**Comment by danielcolinjames** [comment]
@MohdImran001 awesome! I can't assign it to you from the GitHub app right now for some reason, but consider yourself assigned to this issue 😊
