### ISSUE TITLE
Ensure all API calls use helium-js

### ISSUE THREAD

**Issue by allenan** [helium/explorer#22]
There are some direct `fetch` calls to the API. We should be using the [helium-js](https://github.com/helium/helium-js) library wherever we can, and should add API functionality there if needed.

**Comment by fredev** [comment]
I've made a search for fetch call, hope this list can help the refactor

- [ ] [/src/pages/HotspotView.js#L90](https://github.com/helium/explorer/blob/e8e139ed67d53601bac31568c4902c98ea8a9941/src/pages/HotspotView.js#L90)
- [ ] [/src/pages/Index.js#L29](https://github.com/helium/explorer/blob/e8e139ed67d53601bac31568c4902c98ea8a9941/src/pages/Index.js#L29)
- [ ] [/src/pages/Index.js#L40](https://github.com/helium/explorer/blob/e8e139ed67d53601bac31568c4902c98ea8a9941/src/pages/Index.js#L40)
- [ ] [/src/pages/Index.js#L57](https://github.com/helium/explorer/blob/e8e139ed67d53601bac31568c4902c98ea8a9941/src/pages/Index.js#L57)
- [ ] [/src/pages/RichList.js#L18](https://github.com/helium/explorer/blob/e8e139ed67d53601bac31568c4902c98ea8a9941/src/pages/RichList.js#L18)

**Comment by cokes518** [comment]
For hackathon: let us know if there are any changes you need help clarifying

**Comment by Wachiwi** [comment]
Short question: Is this still up to date? The referenced areas were already refactored during the migration from create-react-app to next.js (if I understood it correctly).

**Comment by danielcolinjames** [comment]
hey @Wachiwi, you're right, some of the referenced areas above are probably already changed, but I believe there are still some "manual" fetch calls in various places. some of them might not actually be easily solved through without adding functionality to helium-js... so I think I'm going to remove the hackathon label from this one for now since that would be a bit more of an involved change and need some discussion about the best way to proceed
