### ISSUE TITLE
State Channel Open Amount is Wrong Unit

### ISSUE THREAD

**Issue by lthiery** [helium/explorer#226]
The state channel open `Amount` is using HNT instead of DC: https://explorer.helium.com/txns/7ZQzjdoVuPI_CuheB7oyoESl5UBJ0QH0bTOovRhY0dM

Showing them in raw DCs is probably recommended (or maybe USD equivalent?)

![image](https://user-images.githubusercontent.com/1606640/108917346-715f5b00-75e4-11eb-97c1-bd6580a6a33a.png)

**Comment by danielcolinjames** [comment]
hmm when I do `console.log(txn.amount)` for the URL above, it gives this:
![Screen Shot 2021-02-25 at 1 55 29 PM](https://user-images.githubusercontent.com/10648471/109224841-5706b800-7771-11eb-996d-b316c528fb90.png)

@allenan do you know if the "HNT" there would be because of a helium-js thing or an API thing?

could manually change it to show DC instead, but that feels like the wrong solution
