### ISSUE TITLE
Issue with CSV export time range

### ISSUE THREAD

**Issue by allenan** [helium/explorer#23]
There are reports that the CSV export doesn't respect the provided time frame under certain circumstances. 

See discord for context:
https://discordapp.com/channels/404106811252408320/404106811252408322/750427951002288258

**Comment by cokes518** [comment]
prioritize for tax season.

**Comment by jiceman** [comment]
I suspect that a bag may exist in a conversion from local time to UTC. The export is in UTC. It is not clear what time zone the input uses. And, it is not clear what is desired. For example, If I want all the transaction for a particular day, is that the UTC day, or a day in the local time zone. 

It may also be helpful to allow a time zone to be specified for both the input and also the export. It may be that time is correct now, but it is difficult to understand without the time zone information. I have been exporting for whole UTC days (since I am not clear what else we can do) and find I need to enter some "slop" on both ends to be sure that I don't miss any transactions.

**Comment by mfalkvidd** [comment]
I was bit by this as well. There seems to be a caching issue, or some other randomness.

When I first made the export, for the time period `2021-05-17` to `2021-06-01`, the topmost entry in the csv file was timestamped `2021-05-31T21:59:37.000Z`.
The export was made at `2021-06-01 07:46 UTC`.

I realized that there must be some missing entries (we definitely had transactions after 21:59), so I did another export for the time period `2021-05-17` to `2021-06-02` (so 1 day longer). From this export, the topmost entry in the csv file was `2021-06-01T07:11:02.000Z`.

I then made another export for the initial period (`2021-05-17` to `2021-06-01`). The export was made at `2021-06-01 07:53 UTC`. Now the topmost entry in the csv file is timestamped `2021-06-01T07:46:00.000Z`. There are 79 lines more in this csv file than the one I made at 07:46. The new lines have timestamps between `2021-05-31T23:10:36.000Z` and `2021-06-01T07:46:00.000Z`.

I find this super scary. We have an API for transaction data, with an inconsistent behavior.

**Comment by cokes518** [comment]
We'll be retiring csv export in explorer v2 and directing users to community created tools.

**Comment by jiceman** [comment]
Which community tools provide a good data export function?

**Comment by mfalkvidd** [comment]
@cokes518 any update on jiceman's question?
