### ISSUE TITLE
Hotspot not showing reward scale

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#258]
This Hotspot is not displaying its reward scale on explorer, despite having one returned by the API:

https://api.helium.io/v1/hotspots/112LpUHTffFD1btYyzdh7ggwiGccDvR2BikYHmUyAB15SgAUhmph
<img width="162" alt="image" src="https://user-images.githubusercontent.com/19331274/110188294-0249e980-7dd0-11eb-9330-214f44ccf57b.png">

https://explorer.helium.com/hotspots/112LpUHTffFD1btYyzdh7ggwiGccDvR2BikYHmUyAB15SgAUhmph
<img width="507" alt="image" src="https://user-images.githubusercontent.com/19331274/110188253-f3633700-7dcf-11eb-9d7d-8657028cfbe0.png">

**Comment by cokes518** [comment]
might be a caching issue, abhay can see it but I can't.
<img width="860" alt="image" src="https://user-images.githubusercontent.com/19331274/110188372-450bc180-7dd0-11eb-81a6-756743f040cc.png">

**Comment by danielcolinjames** [comment]
yeah fairly certain it's a caching thing. with newly added hotspots there won't be a reward scale for a little while in the API response. but yeah if you're seeing a disparity between API and the Explorer that's because of `getStaticProps`. I think that's covered by #233 , so I'll close this for now
