### ISSUE TITLE
Show relay status on hotspot details page

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#295]
Let a user know if their Hotspot's internet connection is being relayed.

Add a 'pill' next to Sync status that show indicates whether it is being relayed. <🔴 Relayed>. If it not being relayed, do not show the pill. Indicator should be red.

On hover, it should read "Hotspot is being relayed and may affect mining. Go to https://intercom.help/heliumnetwork/en/articles/3207912-troubleshooting-network-connection-issues to learn more about opening ports for the Hotspot.

**Comment by danielcolinjames** [comment]
thanks for documenting this @cokes518!

I like this design, I think it's better as its own pill for now, so people aren't alarmed and thinking relay is a new problem that just started happening with their hotspot. to be honest I didn't even know what relay meant until the discussion came up today, so I think we'll definitely need some time for educating before we combine it with the "online" indicator in the UI and this feels like a good design for an in between step

@PeterMain do you agree? and any thoughts on the icon shape? for reward scale it's a subtle hex icon I pulled from Figma somewhere. should this Relay indicator be just a circle for now like the online indicator? or maybe we could visually refactor the whole "status" bar since it might look a little crowded in this style with 3 separate pills

probably won't start working on this until monday or tomorrow at the earliest so no rush

**Comment by PeterMain** [comment]
Adding this relayed indicator has got me wondering what other network information we have worth exposing.

For now I agree, a separate pill probably makes sense, but in the future refactoring as 'degrees' of 'online' makes better sense.

How analogous is this to NAT setting? - that comes up a lot in xbox live world. Hadn't heard the term relaying before.
