### ISSUE TITLE
Proposal: Network Usage Section

### ISSUE THREAD

**Issue by PeterMain** [helium/explorer#514]
Goal: To highlight network usage both quantitively but also showcase selected/known network users and also present the network as a dynamic and active system.

**How would it work?**
In this section (and potentially others) the map would indicate in pseudo-realtime which hotspots were relaying data, and would cycle through, say 10 blocks worth, of data relay transactions.

A series of widgets would provide top-level indicators on 'Active Devices', '% Active', 'Hotspots Relaying data (30D)','Most connected city' etc...

A tab item would list companies (perhaps map centres to their HQ?) and display some information about them that we would initially curate, with the goal that others could be added via PR.

<img width="1688" alt="Network USage" src="https://user-images.githubusercontent.com/3613880/124136580-d0dee300-da7c-11eb-9742-8daf8569b562.png">

**Comment by cokes518** [comment]
@PeterMain 

We had a discussion with router/console/api about how the types of data we can show. The TLDR: we won't be able to show console accounts, device count, or % active devices because we don't have visibility into other routers on the network (we own 2, the network has 15 and growing).

Instead, the team thinks that focusing on how much data the Hotspots transfer, and most active Hotspots can also speak to the same usage story.

New Stats Proposal:
total packets
total DC
HNT burned for that period
active city  (city with most Hotspots relaying data)
relaying hotspots (how many)
active hotspots relaying data
heatmap of hotspots sending data

**Comment by cokes518** [comment]
Companies should each have a tag
* tag filtering (apply to community tools)

**Comment by anthonyra** [comment]
I stumbled upon this and it looks really cool, but I'd agree based on the router discussion. Unless there was a way for those operators to "register" to show up on the explorer? Just a thought and maybe too much work for the reward
