### ISSUE TITLE
Wrong Flag showing on City search for city in Kosovo

### ISSUE THREAD

**Issue by waveform06** [helium/explorer#709]
### What happened?

Discord user Smiler reported that the Serbian Flag is showing on explorer when he searches for the city Prishtina - which is in the country of Kosovo
![Prist](https://user-images.githubusercontent.com/44499545/134826692-aa0842cc-88d9-4ac2-bd4f-d70ef1708d75.PNG)
e

The correct flag should be
https://www.google.com/search?q=kosovo+flag&oq=kosovo+flag&aqs=chrome..69i57j0i512l9.2855j0j7&sourceid=chrome&ie=UTF-8
It was correct before
https://discordapp.com/channels/404106811252408320/404106811252408322/891807789645717506

### URL

on explorer.helium.com go hotspots > cities then search for Prishtina.
The dropdown shows the wrong country flag against city name

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by abhay** [comment]
Potentially bad data coming back from mapbox query or incorrect use of that data. 

Seems like the flag is available in the library if we provide the right country code: 

![xk](https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/xk.svg)

**Comment by danielcolinjames** [comment]
this does appear to be bad data coming back from Mapbox. it looks like they have Kosovo's country code as "rs". I've been doing some reading on Mapbox's forward geocoding API (which is what powers this specific type of search result) but not sure if there's an easy fix for this.

here's what comes back from Mapbox for the query of "prishtina":
```JSON
{
    "id": "place.18826890154875620",
    "type": "Feature",
    "place_type": [
        "place"
    ],
    "relevance": 1,
    "properties": {
        "wikidata": "Q25270"
    },
    "text": "Prishtinë",
    "place_name": "Prishtinë, Prishtina, Kosovo",
    "bbox": [
        21.090143,
        42.573119,
        21.498125,
        42.817035
    ],
    "center": [
        21.16667,
        42.66667
    ],
    "geometry": {
        "type": "Point",
        "coordinates": [
            21.16667,
            42.66667
        ]
    },
    "context": [
        {
            "id": "region.12072117925875620",
            "wikidata": "Q3625575",
            "text": "Prishtina"
        },
        {
            "id": "country.6843497085122040",
            "wikidata": "Q1246",
            "short_code": "rs",
    country code here ^^^^^^^^^^ is wrong
            "text": "Kosovo"
        }
    ]
}
```

@bschreck, any ideas here? I believe this is related to #667. if I remember correctly, I added the country flag onto your PR. maybe the simplest solution is just not showing the flag since Mapbox seems to be using a different set of country codes than the rest of Explorer / Helium API (which I believe is using Google Maps geocoding behind the scenes)

but I do think the flag goes a long way to enhancing the search results so ideally we can find a way to get the country flags working and fix this discrepancy. I might contact Mapbox about this too.

**Comment by waveform06** [comment]
Country code should be XK according to the hex plans for PoC v11 https://github.com/gradoj/hplans/blob/main/regions.csv

**Comment by cokes518** [comment]
it's possible that the library we use to pull the flag icon is incorrect. we're looking into it.

**Comment by marepleb** [comment]
Kosovo is Serbia!
