### ISSUE TITLE
[Bug]: Allow user to enter full name of known hotspot in "Search" box 

### ISSUE THREAD

**Issue by mjohngreene** [helium/explorer#735]
### What happened?

Not sure if this is really a bug so much as a feature request.  And it is definitely not urgent.

When looking to pull up a hotspot on Explorer, the user has to wait until a search of the names in use based on the characters typed returns a match and then has to select the correct/desired result from a list.  This behavior/series of steps is necessary even if the user knows the full name.  And if the user knows the full name and hits enter after typing it in, the field just goes blank and does not return anything.

From a UX perspective, it seems as though it would be heaps better to allow the user to type the full name of the hotspot in, hit enter, and get the desired result without any extra steps involved.  This might tweak how/when the search function queries the API for the correct hotspot name string.  And it likely would require some additional "error hanlding" be created for errant names/no results.  However, such functionality is very common and it, therefore, seems it would be worthwhile from a UX perspective.

### URL

https://explorer.helium.com/ and https://explorer.helium.com/hotspots

### What browsers are you seeing the problem on?

Brave

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by danielcolinjames** [comment]
so because the "animal name" is derived from a hotspot's blockchain address, it's actually not possible to know a hotspot's blockchain address from just its full animal name, so we actually do have to wait for the API's response in order to direct the browser to that page, even if you know the full animal name

but you're right that the UX of using the search bar can definitely be improved in a handful of ways, so I've addressed the UX parts of your feature request in the PR here: #739

**Comment by mjohngreene** [comment]
Makes sense.  I figured there must be a reason as I couldn't imagine Team
Helium allowing such a thing!

Thanks for the feedback and otherwise handling.
