### ISSUE TITLE
Add Earnings Performance widget to /hotspots

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#768]
it's important to show how a Hotspot is earning compared to the average Hotspot on the network and to set earnings expectations.

On a Hotspot page, add a new widget "Earnings Performance"
This widget will compare the Hotspot's 24h earnings with the network's emissions for Proof-of-coverage and data transfer.

To get the network rewards:
https://api.helium.io/v1/rewards/sum?min_time=-1%20day&bucket=day

look up `rewards`, then multiply that by the % allocation for PoC and data transfer. use chain vars to tabulate this. then divide that number by the number of Hotspots on the network.

cache this data.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/19331274/144910048-cad8c444-5fd4-4af6-bb8e-0711d302b803.png">

**Comment by danielcolinjames** [comment]
I'm wondering if this would be better/more useful if it was included inside the Rolling Earnings widget somehow (I asked @PeterMain if he had any thoughts). because then it could also be shown for each timeframe

if so, then the main thing I'm thinking is it'll be calculating the average earnings, using _today_'s total hotspot count (or hotspot count at the time of calculation/whenever the cache gets updated), which could actually be a pretty different number than 30 days ago

e.g. for the past 30 days, we get an average of: 3.68885074 HNT per hotspot, by the calculation:

([2,311,331.06885322 HNT mined in the past 30 days](https://api.helium.io/v1/rewards/sum?min_time=-30%20day) * [0.61 hotspot-eligible rewards](https://api.helium.io/v1/vars?keys=poc_challengers_percent,poc_challengees_percent,poc_witnesses_percent,dc_percent)) / [382,209 total hotspots](https://api.helium.io/v1/stats/counts)

but that's assuming that every one of the 382,209 hotspots was earning in the past 30 days (some are new in that 30 days, some have been offline the whole time)

maybe I'm overthinking it or missing something, but figured I'd document my thoughts here

**Comment by cokes518** [comment]
> but that's assuming that every one of the 382,209 hotspots was earning in the past 30 days (some are new in that 30 days, some have been offline the whole time)

that's exactly why I didn't include average 30d earnings for the network, as so many Hotspots are being added a day. The average earned per Hotspot would be underestimated. 

7d average earnings might be an interesting stat to keep. It can help summarize network-effects and let you compare to the average, even if there are extraneous factors affecting mining.

**Comment by PeterMain** [comment]
![EQ](https://user-images.githubusercontent.com/3613880/145193359-28e7aea4-11fa-4964-8ea2-e65ec824ee2a.png)

My proposal would be to **_only_** show a 7 Day metric. I don’t think there are enough ‘earning datapoints’ for a 1D metric to be useful; the value would vary too much. Conversely, the 30D wouldn’t respond quickly enough for users to feel like their setup changes were having a noticeable effect, requiring wait of a few days before their rolling average changed.

Extending Coco’s thinking further, one idea i had was forming some sort of ‘Earning Quotient’ metric similar to IQ. You are given a single value multiplier factor (or indexed around 100 as average) for how well below and above average you are. It would also give us a clean, independent metric plot as a map layer.

New Hotspots would only be given an EQ after at least 7 Days of earning data.

Having one single number over one time-frame allows the community to easily compare performance.
