### ISSUE TITLE
Draw Map of Hotspots in Consensus

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#92]
A request from Andrew T - 
visualize consensus membership by plotting hotspot locations on a map.

example consensus group:
https://explorer.helium.com/txns/vCaP6J1b90dnXP3WrrOfdzD-IDqvUEgbZSrlb1XbpZk

**Comment by danielcolinjames** [comment]
Hey @madninja, do you think it would be possible to include the lat/lon of all 16 consensus group hotspots in the API response for a txn of type `consensus_group_v1`? I'm trying to plot them all, but I think right now the only way to do it is to make 16 requests of hotspot IDs to get their lat/lons

Right now it returns an array `members` of each hotspot's address in string format. It would be awesome if each element in `members` had:
- latitude
- longitude
- hotspot address
instead of just the hotspot address string

Let me know if that might be doable! For now, I can just do it the hacky way and get the hotspot lat/lons by pinging the API for each address.

**Comment by madninja** [comment]
> Hey @madninja, do you think it would be possible to include the lat/lon of all 16 consensus group hotspots in the API response for a txn of type `consensus_group_v1`? I'm trying to plot them all, but I think right now the only way to do it is to make 16 requests of hotspot IDs to get their lat/lons
> 
> Right now it returns an array `members` of each hotspot's address in string format. It would be awesome if each element in `members` had:
> 
> * latitude
> * longitude
> * hotspot address
>   instead of just the hotspot address string
> 
> Let me know if that might be doable! For now, I can just do it the hacky way and get the hotspot lat/lons by pinging the API for each address.

Yes, that should be possible. Let’s take it to a GH issue on blockchain-http?
